### PR TITLE
Update main.md

### PR DESCRIPTION
**Pull request by myaghobi**
"Migrations" added to "User Plugins".

### CODE REVIEW

**Comment by n0nag0n** [comment]
I made a new issue in your repo with a few recommended changes. GREAT little plugin you've made!

**Comment by myaghobi** [comment]
Thank you, Austin.
I'm just curious, is there any rules for plugins to display them in the "User Plugins" list?

**Comment by n0nag0n** [comment]
No there aren't any hard rules, I'm just trying to set you up for success. We also want to maintain an image that we are positive, forward thinkers instead of doing practices that are old and outdated.

**Comment by myaghobi** [comment]
If there is some rules or policy for that, I would like to read, otherwise, I expect you to review just the changes in this pr.

**Comment by n0nag0n** [comment]
I talked with @ikkez and for now since we don't have anything formal we'll pull it in. In the future we'll plan on creating guidelines though for new submissions to at least create a base "quality" for user contributed stuff.

**Pull request merged**
